python3: can't open file 'bash': [Errno 2] No such file or directory
